/* eslint-disable @next/next/no-page-custom-font */
import { Loading } from "components/Loading";
import { Select } from "components/Select";
import { useApi } from "hook/useApi";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/home.module.css";

const Home: NextPage = () => {
  const { options, loading } = useApi();

  if (loading) {
    return <Loading />;
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Test lintick</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Lato&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Select options={options} placeholder="Select and item" />
    </div>
  );
};

export default Home;
